### ISSUE TITLE
bug: User Creation Error using username and password

### ISSUE THREAD

**Issue by ahamedzoha** [logto-io/logto#1798] opened 2022-08-20 11:22 UTC
### Describe the bug
Logto is up and running in render.com along with its PostgreSQL DB. 

Creating a user using a username and password results in an unknown error in the front-end. But, while checking Audit Logs and User Management, the created user and its events show up as successful. Despite user creation, cannot log in using the user credentials. Says `Unknown error. Please try again later.` Logging in using a social connector (Google OAuth) works fine. Added step-by-step screenshots for ease of understanding. 

### Expected behavior
User creation and redirection to set redirect URL

### How to reproduce?
Create a Dockerfile in a GitHub repo
Only add `FROM svhd/logto:1.0.0-beta.5`
Connect Render.com to that GitHub repo
Create and run a PostgreSQL 
Set ENV Variables
Integrate the API in the NextJS Application as per the documentation (getting started guide in the logto admin panel)
Call `/api/logto/sign-in` using a button

### Context

OS: 

Environment: Docker Image at render.com 

Logto version: v1.0.0-beta.5

Node version: 16

Postgres version: 14.0.+

Command of starting Logto: Image is automatically deployed and runs on every push from a Github repo. ENV variables are provided in render.com.

### Screenshots

1. Creating a user using a username and password
![image](https://user-images.githubusercontent.com/13367662/185742580-e319d612-6e5a-454d-aecc-311bb0d54d87.png)

2. Audit Log shows a successful event
![image](https://user-images.githubusercontent.com/13367662/185742709-f802cccb-99a5-48cd-9046-89414fa54771.png)
![image](https://user-images.githubusercontent.com/13367662/185742760-43c0ec1a-909b-40c9-8ef9-b37402a0278e.png)

3. Cannot log in using the created username and password
![image](https://user-images.githubusercontent.com/13367662/185742844-de0cd8f5-4861-4270-ab49-22c93544e982.png)

4. Despite 3, the User log shows successful login
![image](https://user-images.githubusercontent.com/13367662/185742905-f812b56d-faea-476a-b601-e10da1c3521d.png)

5. Set up a google login connector and that works fine
![image](https://user-images.githubusercontent.com/13367662/185742974-11071082-6a00-4484-8986-6d8ff6c51c2d.png)
![image](https://user-images.githubusercontent.com/13367662/185742989-7f2993a9-dfb4-489f-a1b5-e2fb19ea63ba.png)
![image](https://user-images.githubusercontent.com/13367662/185743013-45557553-9e1d-4cab-aa3c-d76f6e31818e.png)

**Comment by gao-sun** [comment] 2022-08-20 12:44
Thanks for reporting. Taking a look now.

**Comment by gao-sun** [comment] 2022-08-20 13:00
I just tried our dev and a new docker compose environment, but neither of them can reproduce. Username-with-password worked as expected.

@ahamedzoha is the console log accessible in render? It'll be great if we can see the call stack.

@simeng-li @charIeszhao do you guys have a Render account? Maybe this is something related to Render.

**Comment by charIeszhao** [comment] 2022-08-20 13:36
Hi @ahamedzoha, it looks like the API request timed-out when you tried to sign in with your new account.

<img width="293" alt="image" src="https://user-images.githubusercontent.com/12833674/185748404-03eb6c7f-6f89-419c-af1d-e44c9f1a2a0e.png">

We are using [ky](https://github.com/sindresorhus/ky) to send requests and it has a [default request timeout of 10 seconds](https://github.com/sindresorhus/ky#timeout), which means your request will be automatically aborted if the response doesn't return in 10 seconds.

Can you double check if you can reproduce this issue consistently? And if it occurs again, is it the above case?

Thanks!

**Comment by ahamedzoha** [comment] 2022-08-21 18:01
I simply cannot login using username and password. Getting timeout Error. 
![image](https://user-images.githubusercontent.com/13367662/185804474-d108b419-1ea8-4d1c-afdc-de6201f35af3.png)

Right, fails after 10 seconds. 
![image](https://user-images.githubusercontent.com/13367662/185804506-6b4e0e77-997e-4fb8-a12b-51667f08694b.png)

Log of the app instance
![image](https://user-images.githubusercontent.com/13367662/185804598-d944cabd-290f-4a48-9377-49fcb054c21b.png)

Log of DB
![image](https://user-images.githubusercontent.com/13367662/185804639-e99904d8-22f7-4ee4-b8a4-0e16e3c7b9e8.png)

**Comment by ahamedzoha** [comment] 2022-08-21 18:02
**Social sign in (google connector) works perfectly, btw!**

**Comment by charIeszhao** [comment] 2022-08-22 01:17
Can you provide us the link of your server? Would like to try it myself

**Comment by ahamedzoha** [comment] 2022-08-22 09:29
@charIeszhao sure, [https://logto.azazahamed.com/](https://logto.azazahamed.com/)

The initial request might take a long time (30 sec) or fail. Render puts free tier apps to sleep after 15 mins of inactivity.

**Comment by charIeszhao** [comment] 2022-08-24 15:19
@ahamedzoha Sorry for the late response.
I tried your server and could reproduce the same issue. The username + password sign-in ended up in an unknown error, because the request timed-out (10s).

I also tried sending the request to your server through a REST client instead of triggering from browser client to get around ky, and it worked. Got the response in **15s** though, but the status was 200. See screenshot below.

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/12833674/186455808-db77f0fb-3bcf-449e-abed-810943b7b4b3.png">

We discussed this issue internally and it might be caused by insufficient performance of the server, as we are using Argon2 for password encryption, it takes longer than other algorithms.

Can you send us your server profiling/specs?

**Comment by charIeszhao** [comment] 2022-09-01 01:34
@ahamedzoha Please let me know your thoughts. Thanks!

**Comment by ahamedzoha** [comment] 2022-09-01 16:16
Hi @charIeszhao! Sorry for the late reply. The free tier I am using at render.com has a shared CPU with 512MB of RAM. I would be much more comfortable trying it out in a free server tier while learning and implementing the logto solution. I do understand that it is by no means meant to be performant with such low resources. I am planning to use better hardware in production. 

Yes, adding a manual KY timeout env variable would be very helpful as I really don't want to manually change source code, I want you guys to be able to maintain the software 😅! Pulling the image is just so much cleaner.

**Comment by charIeszhao** [comment] 2022-09-02 01:11
OK, thanks for the updates. We'll see what we can do. Cheers!

**Comment by charIeszhao** [comment] 2022-09-17 07:19
@ahamedzoha Hi Zoha, sorry for the long wait. But finally we decided to increase the ky timeout to 20s, which I think would be enough for any server to respond to the client.

You can wait for the next prerelease version (likely released on next Monday or Tuesday), or try to upgrade to `:edge` version of Logto after this PR is merged.

Let me know if you have further questions. Thanks!
Charles

**Closed** 2022-09-17 13:09 UTC
Labels: bug, pending-verification

**Comment by ahamedzoha** [comment] 2022-09-18 09:18
Thank you @charIeszhao! I will eagerly await the next release.
