### ISSUE TITLE
bug: high virtual memory usage

### ISSUE THREAD

**Issue by msmarks** [logto-io/logto#4320] opened 2023-08-12 14:53 UTC
### Describe the bug

I am new to Node.js. I am using the logto 1.7.0 Docker image. Upon startup, it consumes around 40GB of virtual memory. Is this normal? I currently have only about 20 users and 5 applications.

### Context

- [ ] Logto Cloud
- [x] Self-hosted, Logto version = 
  - [x] Container (Docker image)
  - [ ] Raw Node.js

### Screenshots

![image](https://github.com/logto-io/logto/assets/5122973/45ecc198-0a54-44cd-8a97-d55d0837fa3a)

**Comment by charIeszhao** [comment] 2023-08-27 05:16
It is definitely not normal, but we don't have this issue in any of our environments. Is there a way to reproduce this?

**Comment by msmarks** [comment] 2023-09-01 07:28
Thanks for the response, But I have no idea how to reproduce this. If I have some clues, I will come back.

**Comment by charIeszhao** [comment] 2023-09-15 01:44
I'm closing the issue since we are not able to reproduce it at the moment, and it seems to be an unrelated issue to us (might be a node.js memory leak issue?). Let us know if it happens again, and we can reopen the ticket at that time

**Closed by charIeszhao** 2023-09-15 01:44 UTC
Labels: bug, pending-verification
