### ISSUE TITLE
feature request: Add roles to JWTs 

### ISSUE THREAD

**Issue by vavido** [logto-io/logto#3411] opened 2023-03-14 12:23 UTC
### What problem did you meet?
We use logto together with Hasura. To authorize requests, we have an additional backend services that checks the user's roles and forwards them to Hasura. This adds additional request overhead to each GraphQL request.

### Describe what you'd like Logto to have
Ideally, the JWTs would already include all roles for a user, so that we can simply determine the users permission by looking at the JWT attached to the request. 

This would save lots of requests to logto from our backend service and thereby improve performance.

**Comment by gao-sun** [comment] 2023-03-14 12:25
sounds reasonable @wangsijie @simeng-li any ideas?

**Comment by wangsijie** [comment] 2023-03-14 13:12
We recommend using "scope" instead of "role", so there is only "scope" in the JWT. However, for Hasura, it is necessary to use "role", which sounds reasonable. I am thinking whether we should  provider an option for it

**Comment by gao-sun** [comment] 2023-03-15 13:47
maybe we can leverage the [claim parameter](https://openid.net/specs/openid-connect-core-1_0.html#ClaimsParameter)

**Comment by vavido** [comment] 2023-03-15 15:21
@wangsijie For our case it does not really matter wether it's called "role" or "scope" in the JWT as we have our own endpoint that interprets the JWT for Hasura anyway. 

It's only important that the roles are present in the JWT so we don't need additional requests.

**Comment by wangsijie** [comment] 2023-03-31 04:29
@vavido we have support for Hasura auth, can you please check this doc: https://github.com/hasura/learn-graphql/pull/948 (still waiting to merge)

Feel free to reopen anytime.

**Comment by wangsijie** [comment] 2023-03-31 04:35
Sorry, you want to improve performance, then the solution is not suitable.

**Comment by ashitikov** [comment] 2023-04-03 16:23
+1 for this

**Comment by vavido** [comment] 2023-04-04 09:40
Unfortunately, the Hasura endpoint alone is not sufficient for our use case because:
- We have some additional logic in our Authentication hook that allows for features like `admin` users to see the application with the permissions of other users
- We have some additional endpoints in our backend application that do not interact with Hasura and would benefit from knowing the users roles directly from the JWT

**Comment by wangsijie** [comment] 2023-05-18 02:54
The customization of additional claims in tokens is a great feature, unfortunately, it is not currently in our product roadmap.

However, we do have a workaround that could help you achieve your desired result:

1. Create roles such as admin, manager, and vendor.
2. Next, create a scope with the same name and assign it to each role you created.
3. Finally, when initializing the Logto client, set all scopes to the "scopes" configuration.

```ts
const logtoClient = new LogtoClient({
  // Other configs
  // ...
  scopes: ['admin', 'manager', 'vendor'],
});
```

To learn more about client configuration for RBAC, check this [doc](https://docs.logto.io/docs/recipes/rbac/protect-resource/#client)

By doing this, the access token will contain all the scopes that the user has access to. 

@vavido We hope this solution works for you. Please let us know if you have any further questions or concerns.

**Comment by gao-sun** [comment] 2023-07-17 13:32
After discussion, we can go with the [claims parameter](https://github.com/panva/node-oidc-provider/blob/main/docs/README.md#featuresclaimsparameter) to implement this without affecting the original scope mappings.

**Comment by gao-sun** [comment] 2023-07-20 08:18
ok, after investigation, the claims parameter approach needs intensive SDK update. we'll go with scopes then

**Comment by kswzr** [comment] 2023-09-20 12:36
@gao-sun what is the current timeline for this feature?

**Comment by Dav-id** [comment] 2023-09-21 10:42
This is something that will be hugely valuable for me. I am using the .NET client and at the moment roles inside of LogTo are not usable if they are not passed into the client. 

My very, very crude work around is to use the custom_data and parsing it with a custom filter in my application. This is not ideal and is only just a usable work around for very few users.

**Closed** 2023-10-07 10:20 UTC
Labels: enhancement, status/planned, component/core

**Comment by gao-sun** [comment] 2023-10-09 04:06
let me know if the new version resolves this issue

**Comment by Dav-id** [comment] 2023-10-09 08:37
Hi @gao-sun thanks for this. I can confirm when requesting the "roles" scope in my .NET startup class I am receiving the roles in the claims. 

           
```
options.Scopes = new string[] {
      LogtoParameters.Scopes.Email,  
      LogtoParameters.Scopes.Phone,  
      LogtoParameters.Scopes.CustomData,
      LogtoParameters.Scopes.Identities,  
      **"roles"**
  };
```


The only trouble now is the default .NET role claim type is "role" and not "roles". I am looking into the LogTo.AspNetCore.Authentication library to see if I can change this to map the "roles" claim. 

it should be something like 

`options.TokenValidationParameters.RoleClaimType = "roles";`

Since this isn't currently exposed by the library we will need to update that. Once we have the correct mapping we then can use `User.IsInRole("rolename")` and `[Authorize(Roles = "rolename")]` which will be great. 

Thanks!

**Comment by Dav-id** [comment] 2023-10-09 09:18
I've done some more testing and reverted my LogTo.AspNetCore.Authentication back to the NuGet version and it all seems to be working. I am not sure what I did that broke the .NET side but now its working perfectly.
